version: '1'
services:
  node-app:
    build: .
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:  